### ISSUE TITLE
Better error message for missing xmllint, libxml2, libxslt

### ISSUE THREAD

**Issue by rxaviers** [jquery/api.jqueryui.com#169]
Current error message is clueless when required dependency shared libraries aren't installed:

```
$ grunt build-xml-entries
Running "build-xml-entries:all" (build-xml-entries) task

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:980:11)
    at Process.ChildProcess._handle.onexit (child_process.js:771:34)
```

Shall we have a better (more descriptive / how to address) error message here?

**Comment by sudheerj** [comment]
I got the same error on "grunt deploy" command.Can you please let me know how to install libxml2 and libxslt libraries in windows environment.Thanks in advance..
