### ISSUE TITLE
Check size of all demo frames with theme updates

### ISSUE THREAD

**Issue by scottgonzalez** [jquery/api.jqueryui.com#241]
With the new theme and font size, we should go through all pages to make sure the demo frames are tall enough to show the full demo.

**Comment by jzaefferer** [comment]
Let's do this once the theme update is in master, that should make it a bit easier.

**Comment by arschmitz** [comment]
May want to wait until button lands to since it changes quite a few of them demos in some way.

**Comment by scottgonzalez** [comment]
I suppose it times to finally do this ;-) Any takers?

**Comment by agcolom** [comment]
@scottgonzalez I'm happy to do this... Is it just about checking the demos fit in their frame? 
Should we also check the frames at the bottom of the examples in the api docs pages?
How do you want to proceed?

**Comment by scottgonzalez** [comment]
> @scottgonzalez I'm happy to do this...

Wonderful! :+1:
> Is it just about checking the demos fit in their frame? 

Yup. Specifically on the 1.12 site: http://api.jqueryui.com/1.12/

> Should we also check the frames at the bottom of the examples in the api docs pages?

Those are actually the only demo frames that exist. We don't have inline demos like api.jquerymobile.com, so this is actually a fairly quick task.

> How do you want to proceed?

Just go through the demos and either leave a comment here with any that aren't a good size or send a PR that updates their heights.

Thanks.

**Comment by agcolom** [comment]
@scottgonzalez Brilliant. 

Also, how about these demos: (I thought these were the ones you meant): http://jqueryui.com/demos/, so http://jqueryui.com/accordion/, etc...

**Comment by agcolom** [comment]
@scottgonzalez These examples are still using UI 1.11.4. Will you update to 1.12beta? Or should I check the examples locally?

**Comment by scottgonzalez** [comment]
This is only about api.jqueryui.com.

**Comment by agcolom** [comment]
Yes, but currently is using 1.11.4: 
http://api.jqueryui.com/1.12/accordion/#entry-examples (Or am I looking at the wrong place?)

**Comment by scottgonzalez** [comment]
Oh, yeah, we never updated that. Releasing the API docs during pre-releases is new, so I didn't have a checklist to work from. I'll get that updated and add it to the checklist. Thanks :-)

**Comment by agcolom** [comment]
Perfect :-) I'll get started when that's done :-)

**Comment by scottgonzalez** [comment]
You can now test on http://stage.api.jqueryui.com/1.12/.

**Comment by agcolom** [comment]
Thank you will start checking now (I have 20min before I need to go)

**Comment by agcolom** [comment]
I'll add notes here, so we know what's been done/not done:
- widget:
  - slecetmenu: 250, 250, 250 -> 250, 260, 265 (3 frames)
  - tooltip: 80 -> 100

**Comment by agcolom** [comment]
@scottgonzalez All done :-) Icons and easing are not crucial but I checked the size in case you wanted to avoid scrolling there as well.

**Comment by scottgonzalez** [comment]
Wonderful. Thanks.

**Comment by scottgonzalez** [comment]
Fixed in 18b481496fac4a956e787c8e801280aa7b9efeea.
