### ISSUE TITLE
Autocomplete documentation wrong

### ISSUE THREAD

**Issue by cguilhermef** [jquery/api.jqueryui.com#244]
About source function, was described the "function" parameter :

*A request object, with a __single term__ property, which refers to the value currently in the text input. For example, if the user enters "new yo" in a city field, the Autocomplete term will equal "new yo".*

but this property doesn't exist anymore. The request object is the term typed by user.

The same to "select" event:

select:function(event,ui){} where ui parameter comes undefined. And, "event" becomes "ui" without the "item" property - just ui.value and ui.label - no anymore ui.item.label ui.item.value

**Comment by scottgonzalez** [comment]
It sounds to me like you're not using jQuery UI.

**Comment by cguilhermef** [comment]
I'm sure that I'm using jQuery UI Autocomplete plugin and documentation is wrong or not updated.

http://api.jqueryui.com/autocomplete/#option-source

**Comment by scottgonzalez** [comment]
I highly doubt that, but you can prove it with a reduced test case.

**Comment by cguilhermef** [comment]
autocomplete({
  source: function(request, response) { 
   //request.term return undfined. but just "request" return the typed terms
  },
  select:function(event, ui){
   // ui is undefined
  // event doesn't is an Event but an Object - old ui.item 
}
 });

**Comment by scottgonzalez** [comment]
That's not really helpful. But to prove my point: http://jsbin.com/nesumujisa/1/
