### ISSUE TITLE
Sortable's Opacity API Description Is Misleading

### ISSUE THREAD

**Issue by jtfairbank** [jquery/api.jqueryui.com#246]
`opacity` only gets applied if `helper` is set to "clone" or a function.  It does not seem to get set if `helper` is left as its default "original".  I haven't tested what happens if you set it explicitly to "original".

It'd be good to add this to the opacity option's api documentation, so that people know to set `helper` to "clone".

**Comment by scottgonzalez** [comment]
I'm not sure how you got this impression, but the opacity is applied regardless of what helper is used (even for `helper: "original"`).
