### ISSUE TITLE
Use consistent noun to refer to "nested options" (properties of an option)

### ISSUE THREAD

**Issue by jzaefferer** [jquery/api.jqueryui.com#247]
We currently use both "settings" and "properties" when talking about options. Since we also use "setting" as a verb, I prefer to avoid that when referring to properties of an option, like properties of the `classes` option.

Should be a simple search and replace (or not, as usual). Would like some input before making the change though. /cc @agcolom @arthurvr @kswedberg

**Comment by scottgonzalez** [comment]
@agcolom @arthurvr @kswedberg Thoughts?

**Comment by arthurvr** [comment]
I prefer 'settings' but that's just a personal opinion.

**Comment by agcolom** [comment]
I agree we should be consistent with the wording. My preference goes to "properties". I'd like the opinion of a native speaker also. @kswedberg @scottgonzalez. I don't any any objections for settings if the majority votes for that.

**Comment by scottgonzalez** [comment]
I prefer properties because that's what they are. They're properties of an object.

**Comment by agcolom** [comment]
Same here, I always use properties when referring to the properties of an object.

**Comment by kswedberg** [comment]
properties :+1:

**Comment by jzaefferer** [comment]
Properties it is! I've created a PR, please take a look: #251
