### ISSUE TITLE
Document classes option

### ISSUE THREAD

**Issue by scottgonzalez** [jquery/api.jqueryui.com#256]
https://github.com/jquery/jquery-ui/pull/1411

**Comment by jzaefferer** [comment]
Need to document:

* classes option for widgets having it, including any default properties, if present:
  * accordion: `{ "ui-accordion-header": "ui-corner-top", "ui-accordion-header-collapsed": "ui-corner-all", "ui-accordion-content": "ui-corner-bottom" }`
  * autocomplete: `{}`
  * dialog: `{ "ui-dialog": "ui-corner-all", "ui-dialog-titlebar": "ui-corner-all" }`
  * menu: `{}`
  * progressbar: `{ "ui-progressbar": "ui-corner-all", "ui-progressbar-value": "ui-corner-left", "ui-progressbar-complete": "ui-corner-right" }`
  * resizable: `{ "ui-resizable-se": "ui-icon ui-icon-gripsmall-diagonal-se" }`
  * selectmenu: `{ "ui-selectmenu-button-open": "ui-corner-top", "ui-selectmenu-button-closed": "ui-corner-all" }`
  * slider: `{ "ui-slider": "ui-corner-all", "ui-slider-handle": "ui-corner-all", "ui-slider-range": "ui-corner-all ui-widget-header" }`
  * spinner: `{ "ui-spinner": "ui-corner-all", "ui-spinner-down": "ui-corner-br", "ui-spinner-up": "ui-corner-tr" }
  * tabs: `{ "ui-tabs": "ui-corner-all", "ui-tabs-nav": "ui-corner-all", "ui-tab": "ui-corner-top", "ui-tabs-panel": "ui-corner-bottom" }`
  * tooltip: `{ "ui-tooltip": "ui-corner-all ui-widget-shadow" }
* Widgets using _addClass without defining a classes option: draggable, droppable, selectable, sortable (what do we document here?)
* New $.Widget methods: `_addClass()`, `_removeClass()`, `_toggleClass()`

Anything else?

**Comment by scottgonzalez** [comment]
> Widgets using _addClass without defining a classes option: draggable, droppable, selectable, sortable (what do we document here?)

We document the automatic cleanup for destroy. That just goes into the `_addClass()`, etc. docs, nothing for the actual widgets.

**Comment by arschmitz** [comment]
@scottgonzalez those have a classes option draggable has `ui-draggable`, `ui-draggable-disabled`, `ui-draggable-dragging`, `ui-draggable-handle` etc...

**Comment by scottgonzalez** [comment]
I thought he was referring to using `_addClass()` with just extra classes, no keys.

**Comment by arschmitz** [comment]
DOH!! menu should not be `{}` :(

**Comment by jzaefferer** [comment]
I was referring to widgets that don't specify `options.classes` at all.

Since it looks like @arschmitz has some more work to do to actually finish this, I'll wait for that before putting more work into this.

**Comment by arschmitz** [comment]
@jzaefferer no those should not be defined at all in the actual widget was the :(. What i'm trying to point out is that every widget in terms of the api docs define a classes object. We don't define them in the code though if their values are `undefined`, like the ones i mention above. The base widget adds `ui-widgetname-disabled` for every widget. 

For example draggable is 100% correct in the code but in the api the classes option will be 

```js
{
  "ui-draggable": undefined,
  "ui-draggable-disabled": undefined,
  "ui-draggable-dragging": undefined,
  "ui-draggable-handle": undefined
}
```

**Comment by jzaefferer** [comment]
I still don't understand why some widgets have `classes: {}`, others don't specify the classes option at all.

> no those should not be defined at all in the actual widget was the :(.

I can't parse that sentence.

**Comment by scottgonzalez** [comment]
Anything that has `classes: {}` was supposed to be removed.

**Comment by arschmitz** [comment]
yup that was the :(

**Comment by jzaefferer** [comment]
I'm going to do a PR with the $.Widget docs along with two other widgets, one with `classes` override, one without. Can figure out the best format from there.

**Comment by jzaefferer** [comment]
I've compile the full list of defaults, based on the latest button PR, going through all `ui/` files and looking the the `classes` option, if defined, along with searching for `_addClass()` and `_toggleClass()` calls. @arschmitz could you fact check this list? Special attention to resizable, which might have even more defaults, I can't really tell (see my comment below).

```js
{
	"ui-accordion": undefined,
	"ui-accordion-content": "ui-corner-bottom",
	"ui-accordion-content-active": undefined,
	"ui-accordion-header": "ui-corner-top",
	"ui-accordion-header-active": undefined,
	"ui-accordion-header-collapsed": "ui-corner-all",
	"ui-accordion-header-icon": undefined,
	"ui-accordion-icons": undefined
},
{
	"ui-autocomplete": undefined,
	"ui-autocomplete-input": undefined,
	"ui-autocomplete-loading": undefined
},
{
	"ui-button": "ui-corner-all",
	"ui-button-icon": undefined,
	"ui-button-icon-only": undefined
},
{
	"ui-checkboxradio": undefined,
	"ui-checkboxradio-checked": undefined,
	"ui-checkboxradio-icon": "ui-corner-all",
	"ui-checkboxradio-label": "ui-corner-all",
	"ui-checkboxradio-radio-label": undefined
},
{
	"ui-controlgroup": undefined,
	"ui-controlgroup-horizontal": undefined,
	"ui-controlgroup-vertical": undefined
},
{
	"ui-dialog": "ui-corner-all",
	"ui-dialog-buttonpane": undefined,
	"ui-dialog-buttons": undefined,
	"ui-dialog-buttonset": undefined,
	"ui-dialog-content": undefined,
	"ui-dialog-dragging": undefined,
	"ui-dialog-resizing": undefined,
	"ui-dialog-title": undefined,
	"ui-dialog-titlebar": "ui-corner-all",
	"ui-dialog-titlebar-close": undefined
},
{
	"ui-draggable": undefined,
	"ui-draggable-disabled": undefined,
	"ui-draggable-dragging": undefined,
	"ui-draggable-handle": undefined
},
{
	"ui-droppable": undefined,
	"ui-droppable-active": undefined,
	"ui-droppable-hover": undefined
},
{
	"ui-menu": undefined,
	"ui-menu-divider": undefined,
	"ui-menu-icon": undefined,
	"ui-menu-icons": undefined,
	"ui-menu-item": undefined,
	"ui-menu-item-wrapper": undefined
},
{
	"ui-progressbar": "ui-corner-all",
	"ui-progressbar-complete": "ui-corner-right",
	"ui-progressbar-indeterminate": undefined,
	"ui-progressbar-overlay": undefined,
	"ui-progressbar-value": "ui-corner-left"
},
{
	"ui-resizable": undefined,
	"ui-resizable-autohide": undefined,
	"ui-resizable-e": undefined,
	"ui-resizable-ghost": undefined,
	"ui-resizable-handle": undefined,
	// This one can change based on the helper, ghost and animate options O_o
	"ui-resizable-helper": undefined,
	"ui-resizable-n": undefined,
	"ui-resizable-ne": undefined,
	"ui-resizable-nw": undefined,
	"ui-resizable-resizing": undefined,
	"ui-resizable-s": undefined,
	"ui-resizable-se": "ui-icon ui-icon-gripsmall-diagonal-se",
	"ui-resizable-sw": undefined,
	"ui-resizable-w": undefined
},
{
	"ui-selectable": undefined,
	"ui-selectable-helper": undefined,
	"ui-selected": undefined,
	"ui-selectee": undefined,
	"ui-selecting": undefined,
	"ui-unselecting": undefined
},
{
	"ui-selectmenu-button": undefined,
	"ui-selectmenu-button-closed": "ui-corner-all",
	"ui-selectmenu-button-open": "ui-corner-top",
	"ui-selectmenu-button-space": undefined,
	"ui-selectmenu-menu": undefined,
	"ui-selectmenu-open": undefined,
	"ui-selectmenu-optgroup": undefined,
	"ui-selectmenu-text": undefined
},
{
	"ui-slider": "ui-corner-all",
	"ui-slider-handle": "ui-corner-all",
	"ui-slider-horizontal": undefined,
	"ui-slider-range": "ui-corner-all ui-widget-header",
	"ui-slider-range-max": undefined,
	"ui-slider-range-min": undefined,
	"ui-slider-vertical": undefined
},
{
	"ui-sortable": undefined,
	"ui-sortable-handle": undefined,
	"ui-sortable-helper": undefined,
	"ui-sortable-placeholder": undefined
},
{
	"ui-spinner": "ui-corner-all",
	"ui-spinner-button": undefined,
	"ui-spinner-down": "ui-corner-br",
	"ui-spinner-input": undefined,
	"ui-spinner-up": "ui-corner-tr"
},
{
	"ui-tab": "ui-corner-top",
	"ui-tabs": "ui-corner-all",
	"ui-tabs-active": undefined,
	"ui-tabs-anchor": undefined,
	"ui-tabs-collapsible": undefined,
	"ui-tabs-loading": undefined,
	"ui-tabs-nav": "ui-corner-all",
	"ui-tabs-panel": "ui-corner-bottom"
},
{
	"ui-tooltip": "ui-corner-all ui-widget-shadow",
	"ui-tooltip-content": undefined
}
```

**Comment by arschmitz** [comment]
Ok went through every file and verified all these :+1: looks good to me!

**Comment by arschmitz** [comment]
Oh one thing that i thought of while going through these though. Right now with 2 exceptions all "keys" start with `ui-widgetname` the exceptions being `ui-tab` in tabs and most of the selectable keys. Im wondering if we wont to make these all consistent. Selectable should probably wait for the re-write but the one key in tabs could be fixed now.

**Comment by jzaefferer** [comment]
Wenn, we have both "ui-tab" and "ui-tabs". We'd have to change "ui-tab" to "ui-tabs-tab" or something like that. Is that what you had in mind?

I guess for backcompat we can keep adding the old class, that should be easy enough.

**Comment by arschmitz** [comment]
@jzaefferer yup thats exactly what i had in mind a little verbose but consistent. Also thats exactly what i had in mind for backcompat. There is no css associated with the class so nothing to change there.

**Comment by jzaefferer** [comment]
Fixed in the `1-12` branch.
