### ISSUE TITLE
Document any deprecated options now replaced by classes option

### ISSUE THREAD

**Issue by jzaefferer** [jquery/api.jqueryui.com#261]
Tooltip, dialog, what else?

**Comment by scottgonzalez** [comment]
Anything that's deprecated needs to be tracked in tickets. I can take care of tracking down the list, creating the tickets, and updating the docs.

**Comment by scottgonzalez** [comment]
Widget options that were deprecated:
* dialog: `dialogClass`
* droppable: `activeClass`, `hoverClass`
* tooltip: `tooltipClass`

**Comment by jzaefferer** [comment]
I'm going to update #257 to mark the deprecated options as such, using `deprecated="1.12"`.

**Comment by jzaefferer** [comment]
Done. Scott created all the tickets.

**Comment by jzaefferer** [comment]
Closing since the merge to the 1-12 branch won't autoclose...
