### ISSUE TITLE
Tooltip doesn't close for "target=_blank" links

### ISSUE THREAD

**Issue by simonferndriger** [jquery/api.jqueryui.com#264]
When setting a jQueryUI tooltip for a link with `target=_blank`, and clicking on the link, then returning back to the site, the tooltip stays open.

I guess this has something to do with the `mouseout` event being missing in this case: the mouse pointer jumps directly to the new window while never leaving the link in the old window.

**Demo:**
https://jsfiddle.net/2sk2g02L/

---
**Output:**
![image](https://cloud.githubusercontent.com/assets/1435963/7272922/13f05628-e8ef-11e4-9f0e-3bdf0d4a4e64.png)

**Comment by scottgonzalez** [comment]
This is the bug tracker for the API documentation.

Also, see http://bugs.jqueryui.com/ticket/9336.

**Comment by simonferndriger** [comment]
Thanks, but what do I read there: "Opened 2 years ago"!
When will this **** bug be fixed already?

**Comment by scottgonzalez** [comment]
If you read the bug, there's an explanation of the problem and the status is set to can't fix. If there were a known workaround, it'd be in the ticket.

**Comment by simonferndriger** [comment]
Thank you. Unfortunately, I can't access the ticket right now...

"The page you are looking for is temporarily unavailable. Please try again later."

But just at the top of my head: destroying all tooltips, and creating them from scratch, after a new window has opened should do the trick?

**Comment by simonferndriger** [comment]
OK, the page works again. However "It in fact does disappear on mouseout. However, mouseout does not fire when the new window is opened." does not mean that there is no workaround!

**Comment by simonferndriger** [comment]
Can you - or can you not explain, why this workaround is NOT working?
Even if the `mouseout` event is missing when opening a new window, the tooltip should still be closable, right? But in fact, it isn't!

	$(window).blur(function(){
			$('a').tooltip('close');
	});

**Comment by simonferndriger** [comment]
By the way...

	$(window).blur(function(){
		$('a').blur(); // This workaround works, but it should be possible otherwise
	});

**Comment by scottgonzalez** [comment]
Well, that *shouldn't* work, the anchor is not a tooltip instance, the document is. You cannot mix use of delegated tooltips and direct tooltips like that, just check the console.

**Comment by simonferndriger** [comment]
OK, good point.

BUT if I don't mix, i.e. use `$('a')` both times, it still isn't working - why?

https://jsfiddle.net/2sk2g02L/2/

**Comment by scottgonzalez** [comment]
It is working. Don't you see it reappear (as opposed to already being visible) when you switch back? The anchor has focus when the window blurs, so it gets focus when the window is refocused, hence the tooltip is shown again.

**Comment by simonferndriger** [comment]
OK, I see. But it is a bit irritating when something that has been intentionally closed, reopens again - just because it has focus. In my opinion, closing the tooltip should be enough.

**Comment by scottgonzalez** [comment]
I don't think you understand how the DOM works. Look at how many times the anchor GETS focus in your interaction: https://jsfiddle.net/2sk2g02L/3/

**Comment by simonferndriger** [comment]
OK, I see. Maybe this would be a bit a long run, but one could say that closing a tooltip also removes focus IF the window loses focus also...but anyway, removing focus solves the issue.

**Comment by simonferndriger** [comment]
You can put the as workaround in your ticket...

**Comment by scottgonzalez** [comment]
No, one could not say that.

**Comment by scottgonzalez** [comment]
We won't document anything that hurts accessibility like that.

**Comment by simonferndriger** [comment]
As you wish...

**Comment by simonferndriger** [comment]
Another question. This is probably very case specific: but in our case we actually would like to unbind the "focus" from showing the tooltip. So whether an element has focus or not, doesn't play any role anymore for the tooltip.

Because as we use it, the tooltip is a help to decide whether or not a link is interesting to click or not. After it has been clicked, the tooltip doesn't matter anymore.

Is it possible to "free" the tooltip from the focus event/state?

**Comment by scottgonzalez** [comment]
No, that would break accessibility.

**Comment by simonferndriger** [comment]
Well, Scott. This is up to the website using jQuery to decide what they want!

**Comment by simonferndriger** [comment]
By the way: the jQuery tooltip is the only one I know which triggers onFocus. Neither the standard Windows tooltip does that, nor the Google tooltips (for example in Gmail).

It is probably even an unwanted behaviour for most users!

**Comment by daveime** [comment]
@simonferndriger Your suggestion about blurring the anchor does seem to work.

I blur the anchor immediately before opening the new window with "target=_blank", which presumably is removing focus from it. When the opened window is closed, the anchor no longer has focus, hence the tooltip doesn't reappear.

Can't see why there was so much argument over this, when it patently does work.
