### ISSUE TITLE
Tooltip Should Not Trigger on Click

### ISSUE THREAD

**Issue by simonferndriger** [jquery/api.jqueryui.com#268]
Neither the standard Windows tooltip, nor the Google tooltip, nor the tooltips on this very page (Github*) trigger on click.

Now, the jQuery tooltip DOES still show on/after click, I assume this is because it triggers also on focus which is (in most cases) generated by a click.

However, the tooltip helps decide whether or not to click somewhere. When the element is clicked, this decision has already been made. Therefore, the tooltip is not needed anymore.
I understand, that it is desirable to show the tooltip on FOCUS when using tab navigation, however, this also means that the tooltip is still shown on CLICK - which is never desirable and also produces an unsolvable bug: http://bugs.jqueryui.com/ticket/9336.

So I suggest to either give the option to disable showing the tooltip on FOCUS in general, or work out a solution (as Google did it) to show the tooltip on FOCUS, but NOT on CLICK. 

---

*Please consider this for your next release. Thank you.*

<i>*) It is interesting to see, that the tooltips on the right do NOT show on FOCUS, probably because these links keep FOCUS due to the tab navigation. So an active/clicked tab would demonstrate this problem perfectly by probably still showing the tooltip when active...</i>

**Comment by scottgonzalez** [comment]
Please stop filing issues against the API docs.

**Comment by simonferndriger** [comment]
OK then, please tell me where the correct place is for this request?

**Comment by scottgonzalez** [comment]
bugs.jqueryui.com

**Comment by simonferndriger** [comment]
OK, thank you, Scott.
