### ISSUE TITLE
Document $.fn.labels

### ISSUE THREAD

**Issue by arschmitz** [jquery/api.jqueryui.com#270]
We need to add an entry for the new method `$.fn.labels` which attempts to mimic the `control.labels` property from webkit browsers and extends it to work on document fragments as well. This method of course only works on a single element and like other jQuery methods will use the first element in a collection if a collection is passed. It returns a jQuery Collection of all of the labels present which are associated with the input, or an empty collection if there are none.

**Comment by jzaefferer** [comment]
Landed in 1-12 branch.
