### ISSUE TITLE
Dialog does not close correctly

### ISSUE THREAD

**Issue by alxx28** [jquery/api.jqueryui.com#272]
I need to open several dialogs, one after another when focus occurs on a textfield, the first dialog opens correctly, the following one opens when focus occurs, but this does not close correctly.

I am using jquery1.11.4, with jquery 2.1.4 is the same thing.

Demo: http://plnkr.co/edit/HxLE8c84949rUyki6YiE?p=preview

**Comment by scottgonzalez** [comment]
Don't open a dialog on focus of an element. It's bad UX and will result in exactly the situation you're seeing now. When you close a dialog, the previously focused item will gain focus. If focusing that item opens the dialog, you'll be stuck in a never-ending loop.

Also, this is the bug tracker for the api.jqueryui.com site, not jQuery UI itself. Had this been a valid bug, you'd need to report it at http://bugs.jqueryui.com/.
