### ISSUE TITLE
Deprecate/remove http://api.jqueryui.com/focus/

### ISSUE THREAD

**Issue by jzaefferer** [jquery/api.jqueryui.com#277]
This is deprecated/gone, need to update API docs.

**Comment by scottgonzalez** [comment]
Deprecated in 1.11.0, removed in 1.12.0.

**Comment by jzaefferer** [comment]
Marked as deprecated in 541d1971a4a2f04b5e56855b388e554ba401ce4b and removed in 1-12 branch in c5d81d54d88db12d9a68b12bce2fe8f8f9745f3f
