### ISSUE TITLE
ui.handle passed to slider.slide() is not jQuery

### ISSUE THREAD

**Issue by shelldweller** [jquery/api.jqueryui.com#279]
According to http://api.jqueryui.com/slider/#event-slide `ui.handle` is a jQuery object but it is not. It's DOM Element. This probably applies to other slider events as well.

**Comment by scottgonzalez** [comment]
This is the bug tracker for the API docs. Please report code bugs at https://bugs.jqueryui.com/newticket.

**Comment by scottgonzalez** [comment]
I suppose this should stay open if the docs are wrong about the existing versions.
