### ISSUE TITLE
jQuery UI v1.12.0 CDN & blog

### ISSUE THREAD

**Issue by Mottie** [jquery/api.jqueryui.com#305]
It's been over a month (June 8) since jQuery UI v1.12.0 was released. The last [blog post](http://blog.jqueryui.com/) references v1.12.0 RC2.

It appears that only [CDNJS](https://cdnjs.com/libraries/jqueryui) is hosting versions of v1.12.0. The other CDNs last release is still v1.11.4 :
* [Google's CDN](https://developers.google.com/speed/libraries/#jquery-ui).
* [Microsoft CDN](https://www.asp.net/ajax/cdn#jQuery_UI_Releases_on_the_CDN_2).
* [JSDelivr](https://www.jsdelivr.com/?query=jquery%20ui).

I wasn't sure where to post this issue, so I apologize if this is the incorrect location.

**Comment by scottgonzalez** [comment]
We intentionally did not publish a blog post about 1.12.0 because there were a lot of problems during the time of the release. We're waiting for 1.12.1 to do the announcement. We don't have control over the third party CDNs.
