### ISSUE TITLE
What happened to the jQuery UI 1.11 documentation?

### ISSUE THREAD

**Issue by trockefeller** [jquery/api.jqueryui.com#310]
I am trying to view documentation for jQuery UI 1.11 here http://api.jqueryui.com/1.11/ and there are no categories listed. If I go to the link for a "full listing of entries" here http://api.jqueryui.com/1.11/category/all/ I'm getting the "This is somewhat embarrassing, isn’t it?" page saying the resource can't be found. Documentation appears to still be available for 1.10, 1.9, and 1.8, so what happened to 1.11?

**Comment by scottgonzalez** [comment]
The documentation is available now. Sorry about that.
