### ISSUE TITLE
Confusing behavior for jQuery.ajax( success: function() {} ) behavior

### ISSUE THREAD

**Issue by danlo** [jquery/api.jqueryui.com#319]
Greetings,

https://github.com/jquery/api.jquery.com/blob/master/entries/jQuery.ajax.xml#L170

When my application responds with a  status: 200 and NO content
_the success function does *not* fire._
When my application responds with a status: 204 and NO content
_the success function does fire._

I believe that adding a note that success() will not fire with a status code of 200 and no content, and that if no content is present, then to use a status: 204

Regards,

Daniel Lo

Thank you for the great work!

**Comment by scottgonzalez** [comment]
This is for jQuery UI, not jQuery Core.
