### ISSUE TITLE
jqueryUI resizable  and  jqueryUI draggable  can't use cooperatively 

### ISSUE THREAD

**Issue by yuncode** [jquery/api.jqueryui.com#321]
first  move parent Div ,
then resize child Div.  
finally child Div  display incorrectly

if remove the containment option   the case is ok.

demo  [https://codepen.io/oceanstick/pen/LOqGGw](https://codepen.io/oceanstick/pen/LOqGGw)

besides I find jqueryUI resizable can't cooperate with other draggable library, 
so i think jqueryUI resizable have bug .

**Comment by yuncode** [comment]
under below two cases everything is ok.
1.if the parent A doesn't move 。
2. when Initialize , A and B all  don't specify  the helper option.

**Comment by scottgonzalez** [comment]
This is the bug tracker for the web site only.
